#HomeWork 3

The homework must be done individually and submitted online on Canvas. Please submit your final submission files. The submission must be the  *.ipynb* extension file, and outputs (*if any*) in a zip folder.  

## Introduction
In this homework, we will work with distance fields data and perform operations on it. Please submit the code files with the solution.

In [32]:
import numpy as np
from trimesh.voxel.ops import matrix_to_marching_cubes

In [33]:
def load_difis(filename):
    data = np.load(filename)
    cylinder = data['cylinder']
    cube = data['cube']
    return cube, cylinder

## Question 1: Boolean Operations on Distance Fields (10 points)

Write a code snippet to perform Boolean operations of (i) Union (ii) Intersection and (iii) difference of two distance fields. This task is highlighted by a TODO below.


In [34]:
def Union(obj1, obj2):
    # Union operation for two objects
    # obj1 Union obj2
    # TODO: Union operation 
    #union_array = max(obj1,obj2)
    union_array = np.where(obj1>obj2, obj1, obj2)
    return union_array

In [35]:
def Intersection(obj1, obj2):
    # Intersection operation for two objects
    # obj1 Intersection obj2
    # TODO: Intersection operation 
    #int_array = min(obj1,obj2)
    int_array = np.where(obj1<obj2, obj1, obj2)
    return int_array

In [36]:

def Difference(obj1, obj2):
    # Difference operation for two objects
    # obj1 Minus obj2
    # TODO: Difference operation
    #diff_array = min(obj1,-obj2)
    diff_array = np.where(obj1<(-1.0*obj2), obj1, (-1.0*obj2))
    return diff_array


In [37]:
# Parameters that control the distance fields
gridsize = 0.25
origin = [0.0, 0.0, 0.0]

# The distancefields.npz is a numpy array that contains the distance fields of a cube and a cylinder
cube, cylinder =  load_difis('distancefields.npz')

print(cube)
print(cylinder)

[[[0.10416667 0.10416667 0.10416667 ... 0.10416667 0.10416667 0.10416667]
  [0.10416667 0.10416667 0.10416667 ... 0.10416667 0.10416667 0.10416667]
  [0.10416667 0.10416667 0.10416667 ... 0.10416667 0.10416667 0.10416667]
  ...
  [0.10416667 0.10416667 0.10416667 ... 0.10416667 0.10416667 0.10416667]
  [0.10416667 0.10416667 0.10416667 ... 0.10416667 0.10416667 0.10416667]
  [0.10416667 0.10416667 0.10416667 ... 0.10416667 0.10416667 0.10416667]]

 [[0.10416667 0.10416667 0.10416667 ... 0.10416667 0.10416667 0.10416667]
  [0.10416667 0.3125     0.3125     ... 0.3125     0.3125     0.10416667]
  [0.10416667 0.3125     0.3125     ... 0.3125     0.3125     0.10416667]
  ...
  [0.10416667 0.3125     0.3125     ... 0.3125     0.3125     0.10416667]
  [0.10416667 0.3125     0.3125     ... 0.3125     0.3125     0.10416667]
  [0.10416667 0.10416667 0.10416667 ... 0.10416667 0.10416667 0.10416667]]

 [[0.10416667 0.10416667 0.10416667 ... 0.10416667 0.10416667 0.10416667]
  [0.10416667 0.3125  

In [38]:
# Perform the Boolean operations and store the distance fields in new variables
union = Union(cube, cylinder)
intersection = Intersection(cube, cylinder) 
diff = Difference(cube, cylinder)


## Question 2: Distance Fields to Voxel Representation (10 points)

Convert the distance fields obtained in the previous question (distance field outputs of the three operations) to a Voxel representation. Recall the Binary Voxel representation discussed in class. This task is highlighted by a TODO below.

In [39]:

# TODO: Convert Distance Fields to  Binary Voxel Representation
# Need to choose a cutoff for the distance fields and perform a classification for each voxel grid center
union_inouts = union>0
intersection_inouts = intersection>0
diff_inouts = diff>0

## Question 3: Marching Cubes (10 points)

Convert the binary Voxel representation obtained in the previous question to triangular mesh using marching cubes algorithm. The end deliverable of this task is a .STL file for each of the marching cubes output of the three Boolean operations. The use of the trimesh package is preferred, since it is easy to implement the assignment in that.

In [40]:
# TODO: Create Trimesh objects from inouts representation using marching cubes
# Hint: Voxel grid pitch is same as the gridsize
!pip install scikit-image
import trimesh
union_march_cube = trimesh.voxel.ops.matrix_to_marching_cubes(union_inouts, pitch=1.0)
intersection_march_cube = trimesh.voxel.ops.matrix_to_marching_cubes(intersection_inouts, pitch=1.0)
diff_march_cube = trimesh.voxel.ops.matrix_to_marching_cubes(diff_inouts, pitch=1.0)
trimesh.exchange.export.export_mesh(union_march_cube, file_obj = '/Users/ankushmishra/ME_570_Assignment/ME570_Assignment/Assignment3/Union_March_cubes.stl',file_type = "stl")
trimesh.exchange.export.export_mesh(intersection_march_cube, file_obj = '/Users/ankushmishra/ME_570_Assignment/ME570_Assignment/Assignment3/Intersection_March_cubes.stl',file_type = "stl")
trimesh.exchange.export.export_mesh(diff_march_cube, file_obj = '/Users/ankushmishra/ME_570_Assignment/ME570_Assignment/Assignment3/Difference_March_cubes.stl',file_type = "stl")

b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 %\x00\x00:\xcd\x13\xbf:\xcd\x13\xbf:\xcd\x13\xbf\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xbf\x00\x00\x00\x00\x00\x00\x00\xbf\x00\x00\x00\x00\x00\x00\x00\xbf\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf3\x045\xbf\xf3\x045\xbf\x00\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\xbf\x00\x00\x80?\x00\x00\x00\xbf\x00\x00\x00\x00\x00\x00\x80?\x00\x00\x00\xbf\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf3\x045\xbf\xf3\x045\xbf\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xbf\x00\x00\x80?\x00\x00\x00\xbf\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xbf\x00\x00\x00\x00\x00\x00\xf3\x045\xbf\xf3\x045\xbf\x00\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\xbf\x00\x00\x00@\x00\x00\x0